# This file is automatically synced from:
# https://github.com/autowarefoundation/sync-file-templates
# To make changes, update the source repository and follow the guidelines in its README.

name: sync-files

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-files:
    runs-on: ubuntu-22.04
    steps:
      - name: Run sync-files
        uses: autowarefoundation/autoware-github-actions/sync-files@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-labels: |
            tag:bot
            tag:sync-files
          auto-merge-method: squash
